version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile.nodejs
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app

  nginx:
    image: nginx:alpine
    ports:
      - "8082:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./app/build:/usr/share/nginx/html
    depends_on:
      - nodejs
