FROM node:alpine

WORKDIR /app

# Copy the entire application code to the container
COPY . .

# Expose port 3000 for the Node.js application
EXPOSE 8080

# Start Node.js when the container runs
CMD ["node", "index.js"]